src/backend_api/blogs/models.py
from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime
from config.db_settings import DatabaseConnection


Base = DatabaseConnection.base_instance()


class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(20),nullable=False)
    password = Column(String(50))
    creatime = Column(DateTime,default=datetime.now)

src/backend_api/users/models.py
from datetime import datetime
from email.policy import default
from inspect import classify_class_attrs
from xmlrpc.client import Boolean
from sqlalchemy import BOOLEAN, Column, Integer, String, DateTime, true
from config.db_settings import DatabaseConnection


Base = DatabaseConnection.base_instance()


class AuthGroup(Base):
    """权限组分类"""
    __tablename__ = "auth_group"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(20), nullable=False, unique=True)

    def __repr__(self):
        return f"authGroup(id={self.id}, name={self.name})"


class AuthGroupPermissions(Base):
    """权限组权限"""
    __tablename__ = "auth_group_permissions"
    id = Column(Integer, primary_key=True, autoincrement=True)
    group_id = Column(Integer, nullable=False)
    permission_id = Column(Integer, nullable=True)

    def __repr__(self):
        return f"authGroupPermissions(id={self.id}, \
            group_id={self.group_id}, permission_id={self.permission_id})"


class AuthUserGroups(Base):
    """用户权限组"""
    __tablename__ = "auth_user_groups"
    id = Column(Integer, primary_key=True, autoincrement=True)
    group_id = Column(Integer, nullable=False)
    user_id = Column(Integer, nullable=False)
    
    def __repr__(self):
        return f"authGroupPermissions(id={self.id}, \
            group_id={self.group_id}, permission_id={self.user_id})"


class AUthPermission(Base):
    __tablename__ = "auth_permission"

    def __repr__(self):
        return f"authGroup(id={self.id}, name={self.name})"


class AUthUser(Base):
    __tablename__ = "auth_user"
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_name = Column(String(20), nullable=False, unique=True)
    password = Column(String(20), nullable=False)
    is_superuser = Column(Boolean, default=True)
    last_login = Column(DateTime, default=now())
    is_staff = Column(Boolean, default=1)
    is_active = Column()

    def __repr__(self):
        return f"authGroup(id={self.id}, name={self.user_name})"















class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(20),nullable=False)
    password = Column(String(50))
    creatime = Column(DateTime,default=datetime.now)

src/backend_api/blogs/controller.py
from flask import Blueprint, request, render_template


bg = Blueprint("blogs", __name__)


@bg.route("/blogs/<blog_id>", methods=["GET", "POST"])
def operate_blogs(blog_id):
    if request.method == "GET":
        if not isinstance(blog_id, int):
            
        print(blog_id)
        return blog_id
        # return render_template("tem÷plates/blog_editor/")
    if request.method == "POST":
        pass


# @bg.route("/blogs/<blog_id>")
# def 

src/backend_api/users/controller.py
import json
from flask import Blueprint, render_template, request


ul = Blueprint("user_login", __name__)


@ul.route("/login", methods=["GET", "POST"])
def user_login():
    if request.method == "GET":
        return render_template("users/login.html")
    if request.method == "POST":
        return json.dumps({"name": 1})


@ul.route('/register', methods=["GET", "POST"])
def user_register():
    if request.method == "GET":
        return render_template("users/register.html")
    if request.method == "POST":
        return json.dumps({"name": 1})

src/backend_api/users/views.py
class User(object):
    def __init__(self, ) -> None:
        pass

src/templates/blog_editor/preview-blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/css/editor_css/style.css" />
    <link rel="stylesheet" href="../../static/css/editor_css/editormd.preview.css" />
    <title>Document</title>
    <style>            
        .editormd-html-preview {
            width: 90%;
            margin: 0 auto;
        }
    </style>
</head>
<body>
<div id="test-markdown-view">
    <textarea style="display:none;"></textarea>
</div>
<script src="../../static/js/editor_js/jquery.min.js"></script>
<script src="../../static/js/editor_js/editormd.js"></script>
<script src="lib/marked.min.js"></script>
<script src="lib/prettify.min.js"></script>
<script src="lib/raphael.min.js"></script>
<script src="lib/underscore.min.js"></script>
<script src="lib/sequence-diagram.min.js"></script>
<script src="lib/flowchart.min.js"></script>
<script src="lib/jquery.flowchart.min.js"></script>
<script type="text/javascript">
    $(function() {
	    var testView = editormd.markdownToHTML("test-markdown-view", {
            htmlDecode      : "style,script,iframe",  // you can filter tags decode
            emoji           : true,
            taskList        : true,
            tex             : true,  // 默认不解析
            flowChart       : true,  // 默认不解析
            sequenceDiagram : true,  // 默认不解析
        });
    });
</script>    
</body>
</html>

src/templates/blog_editor/submit-blog.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8" />
        <title>图片上传示例 - Editor.md examples</title>
        <link rel="stylesheet" href="../../static/css/editor_css/style.css" />
        <link rel="stylesheet" href="../../static/css/editor_css/editormd.css" />
        <link rel="shortcut icon" href="https://pandao.github.io/editor.md/favicon.ico" type="image/x-icon" />
    </head>
    <body>
        <div id="layout">
            <form method="post" action="http://editormd.ipandao.com/php/post.php">
                <div id="blog-editormd">
                    <textarea class="editormd-markdown-textarea" name="blog-editormd-markdown-doc"></textarea>
                </div>
                <div style="width:90%;margin: 10px auto;">
                    <input type="submit" name="submit" value="提交表单" style="padding: 5px;" /> 
                </div>               
            </form>
        </div>
        <script src="../../static/js/editor_js/jquery.min.js"></script>
        <script src="../../static/js/editor_js/editormd.js"></script>
        <script type="text/javascript">
            $(function() {                
                var testEditor = editormd("blog-editormd", {
                    width: "100%",
                    height: 640,
                    markdown : "",
                    path : 'lib/',
                    dialogLockScreen : false,   // 设置弹出层对话框不锁屏，全局通用，默认为 true
                    dialogShowMask : true,     // 设置弹出层对话框显示透明遮罩层，全局通用，默认为 true
                    dialogDraggable : true,    // 设置弹出层对话框不可拖动，全局通用，默认为 true
                    dialogMaskOpacity : 0.4,    // 设置透明遮罩层的透明度，全局通用，默认值为 0.1
                    dialogMaskBgColor : "#000", // 设置透明遮罩层的背景颜色，全局通用，默认为 #fff
                    imageUpload : true,
                    imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                    imageUploadURL : "./php/upload.php?test=dfdf",
                    saveHTMLToTextarea : true
                    /*
                     上传的后台只需要返回一个 JSON 数据，结构如下：
                     {
                        success : 0 | 1,           // 0 表示上传失败，1 表示上传成功
                        message : "提示的信息，上传成功或上传失败及错误信息等。",
                        url     : "图片地址"        // 上传成功时才返回
                     }
                     */
                });
            });
        </script>
    </body>
</html>

src/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Index</title>

    <!-- Google Font: Source Sans Pro -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../static/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="../../static/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../static/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo" style="color: blue;">
            <b>CoolS Platform</b>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your management</p>
                <form action="">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Username" id="username" value="">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" id="password" value="">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                            </div>
                        </div>
                        <span id="password-tips"></span>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                Remember Me
                            </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="button" class="btn btn-info btn-block" onclick="loginIn()">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>

                <div class="social-auth-links text-center mb-3">
                    <p>- OR -</p>
                    <a href="#" class="btn btn-block btn-info">
                    I forgot my password
                    </a>
                    <a href="{{ url_for('user_login.user_register') }}" class="btn btn-block btn-info">
                    Register a new membership
                    </a>
                </div>
            <!-- /.social-auth-links -->
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
<!-- /.login-box -->
<!-- jQuery -->
<script src="../../static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../static/dist/js/adminlte.min.js"></script>
<script>
    var username = document.getElementById("username");
    var password = document.getElementById("password");
    var payload = JSON.stringify(
        {
            "userName": username.value,
            "passWord": password.value
        }
    )
    // 验证用户名
    function checkUsername() {
        var reg_username = /^[a-zA-Z]{6,10}$/;
        if (!reg_username.test(username.value)) {
            return false;
        } else {
            return true;
        }
    }
    // 验证密码
    function checkPassword() {
        var reg_password = /^\w{6}$/;
        if (!reg_password.test(password.value)) {
            return false;
        } else {
            return true;
        }
    }
    // 焦点验证
    username.onblur = function() {
        checkUsername();
    };
    password.onblur = function() {
        checkPassword();
    }

    // Ajax提交
    function ajaxLogin(data) {
        try {
            xhr = new XMLHttpRequest();
        } catch (e) {
            xhr = new ActiveXObject("Microsoft.XMLHTTP");
        }
        xhr.open("POST", "/login", true);
        xhr.setRequestHeader(
            "content-type", "application/json;charset=UTF-8"
        );
        xhr.send(data);
        xhr.onreadystatechange = function () {
            if (xhr.status == 200) {
                if (xhr.readyState == 4) {
                    console.log("success");
                }
            }
        }
    };

    // 点击 Sign In
    function loginIn() {
        var payload = JSON.stringify({
            "userName": username.value,
            "passWord": password.value
        })
        if (checkUsername() && checkPassword()) {
            ajaxLogin(payload);
        } else {
            alert("Wrong name or password!");
        }
    };
</script>
</body>
</html>

src/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>

    <!-- Google Font: Source Sans Pro -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../static/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="../../static/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../static/dist/css/adminlte.min.css">
</head>
<body class="hold-transition register-page">
<div class="register-box">
	<div class="register-logo" style="color: blue;">
		<b>CoolS Platform</b>
	</div>
  	<div class="card">
    	<div class="card-body register-card-body">
      		<p class="login-box-msg">Register a new membership</p>

			<form action="../../index.html" method="post">
				<div class="input-group mb-3">
					<input type="text" class="form-control" placeholder="Full name" id="fullname">
					<div class="input-group-append">
						<div class="input-group-text">
							<span class="fas fa-user"></span>
						</div>
					</div>
				</div>
				<div class="input-group mb-3">
					<input type="password" class="form-control" placeholder="Password" id="password">
					<div class="input-group-append">
						<div class="input-group-text">
							<span class="fas fa-lock"></span>
						</div>
					</div>
				</div>
				<div class="input-group mb-3">
					<input type="password" class="form-control" placeholder="Retype password" id="retype-password">
					<div class="input-group-append">
						<div class="input-group-text">
						<span class="fas fa-lock"></span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-8">
						<div class="icheck-primary">
							<input type="checkbox" id="agreeTerms" name="terms" value="agree">
							<label for="agreeTerms">
								I agree to the <a href="terms.html">terms</a>
							</label>
						</div>
					</div>
					<!-- /.col -->
					<div class="col-4">
						<button type="submit" class="btn btn-primary btn-block">Register</button>
					</div>
					<!-- /.col -->
				</div>
			</form>

			<div class="social-auth-links text-center">
				<p>- OR -</p>
				<a href="login.html" class="btn btn-block btn-primary">
				I already have a membership
				</a>
			</div>
    	</div>
    <!-- /.form-box -->
  	</div><!-- /.card -->
</div>
<!-- /.register-box -->
<!-- jQuery -->
<script src="../../static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../static/dist/js/adminlte.min.js"></script>
<script>
  var fullname = document.getElementById("fullname");
  var password = document.getElementById("password");
  var retype_password = document.getElementById("retype-password");
  // 校验fullname
  function checkFullName {
    var reg_username = /^[a-zA-Z]{6,10}$/;
    
    if (!reg_username.test(fullname.value)) {
      return false;
    } else {
      return true;
    }
  };
  // 校验password
  function checkPassword {

  };
  // 校验retype-password
  function retypePassword {

  };
</script>
</body>
</html>